### ISSUE TITLE
Hash tags in text may lead to no results 

### ISSUE THREAD

**Issue by cjthornhill** [qmeeus/balanced-view#8]
With some hashtags in the text, sometimes no results are returned. Perhaps, we can strip all hashtags from the text, this seems to work.

**Comment by qmeeus** [comment]
For now, I filtered out the hashtags. I also tried to process them by separating them into words but the results were not better for some reason (I think mostly because you can have hashtags that are not related following each other and textrank treats that as normal text, so we search for unrelated events #CrookedHillary #WitchHunt #BalancedViewIsTheBest)
